title:            "System Programming 2022-1 (SP221)"
author:           "Dewangga Putra Sheradhien"
home:             "/"
log:              "TXT/mylog.txt"
repo:             "https://github.com/dewa251202/sp221/"
